name: school_management
description: "Aplikasi School Management"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  image_picker: ^1.0.4
  file_picker: ^8.0.0
  dio: ^5.9.1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.4
  flutter_dotenv: ^6.0.0
  provider: ^6.1.2
  camera: ^0.12.0
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - .env
